[workspace]
default-members = ["rstmt"]
members = [
  "core",
  "nrt",
  "rstmt",
  "traits",
]
resolver = "3"

[workspace.package]
authors = [
  "FL03 <jo3mccain@icloud.com> (https://github.com/FL03)",
  "Scattered-Systems <support@scsys.io> (https://github.com/scattered-systems)",
]
categories = ["mathematics"]
description = "A complete framework for computational music theory, analysis, and research, with a focus on hypergraphs and topology."
edition = "2024"
homepage = "https://github.com/FL03/rstmt/wiki"
keywords = [
  "analysis",
  "composition",
  "music-theory",
  "research",
  "topology",
]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/FL03/rstmt.git"
rust-version = "1.85.0"
version = "0.0.7"

[workspace.dependencies]
rstmt = { default-features = false, path = "rstmt", version = "0.0.7" }
rstmt-core = { default-features = false, path = "core", version = "0.0.7" }
rstmt-nrt = { default-features = false, path = "nrt", version = "0.0.7" }
rstmt-traits = { default-features = false, path = "traits", version = "0.0.7" }
# custom
contained = { default-features = false, features = ["macros"], version = "0.2.3" }
rshyper = { default-features = false, features = ["macros"], version = "0.1.8" }
rspace = { default-features = false, features = ["macros"], version = "0.0.4" }
variants = { default-features = false, features = ["derive"], version = "0.0.1" }
# concurrency & parallelism
crossbeam = { default-features = false, version = "0.8" }
rayon = { default-features = false, version = "1" }
rayon-core = { default-features = false, version = "1" }
# data structures
hashbrown = { default-features = false, version = "0.16" }
# error-handling
anyhow = { default-features = false, version = "1" }
thiserror = { default-features = false, version = "2" }
# numbers
num-complex = { default-features = false, version = "0.4" }
num-integer = { default-features = false, version = "0.1" }
num-traits = { default-features = false, version = "0.2" }
# randomization
getrandom = { default-features = false, version = "0.3" }
rand = { default-features = false, version = "0.9" }
rand_core = { default-features = false, version = "0.9" }
rand_distr = { default-features = false, version = "0.5" }
# data & serialization
serde = { default-features = false, features = ["derive"], version = "1" }
serde_derive = { default-features = false, version = "1" }
serde_json = { default-features = false, version = "1" }
# macros
itertools = { default-features = false, version = "0.14" }
lazy_static = { version = "1" }
paste = { version = "1" }
smart-default = { version = "0.7" }
strum = { default-features = false, features = ["derive"], version = "0.27" }
# WebAssembly
wasm-bindgen = { default-features = false, version = "0.2" }

# ************* [Profiles] *************
[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = "thin"
opt-level = 2
overflow-checks = true
panic = "abort"
rpath = true
strip = "symbols"

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = "z"
overflow-checks = false
panic = "abort"
rpath = false
strip = "debuginfo"
