[workspace]
default-members = ["rstmt"]
members = [
  "core",
  "macros",
  "nrt",
  "rstmt",
  "traits",
]
resolver = "3"

[workspace.package]
authors = [
  "FL03 <joe@pzzld.org> (https://github.com/FL03)",
  "Scattered-Systems <support@scsys.io> (https://github.com/scattered-systems)",
]
categories = ["mathematics"]
description = "A complete framework for computational music theory and composition based on topological and categorical methods."
edition = "2024"
homepage = "https://github.com/FL03/rstmt/wiki"
keywords = [
  "analysis",
  "composition",
  "music-theory",
  "research",
  "topology",
]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/FL03/rstmt.git"
rust-version = "1.86.0"
version = "0.0.13"

[workspace.dependencies]
rstmt = { default-features = false, path = "rstmt", version = "0.0.13" }
rstmt-core = { default-features = false, path = "core", version = "0.0.13" }
rstmt-macros = { path = "macros", version = "0.0.13" }
rstmt-nrt = { default-features = false, path = "nrt", version = "0.0.13" }
rstmt-traits = { default-features = false, path = "traits", version = "0.0.13" }
# custom
contained = { default-features = false, features = ["derive", "macros"], version = "0.2.4" }
rshyper = { default-features = false, features = ["macros"], version = "0.1.9" }
rspace-traits = { default-features = false, version = "0.0.9" }
variants = { default-features = false, features = ["derive"], version = "0.0.1" }
# benchmarking & testing
criterion = { default-features = false, version = "0.8" }
# concurrency & parallelism
rayon = { default-features = false, version = "1" }
# data structures
hashbrown = { default-features = false, version = "0.16" }
# error-handling
anyhow = { default-features = false, version = "1" }
thiserror = { default-features = false, version = "2" }
# numbers
num-complex = { default-features = false, version = "0.4" }
num-integer = { default-features = false, version = "0.1" }
num-traits = { default-features = false, version = "0.2" }
# randomization
getrandom = { default-features = false, version = "0.3" }
rand = { default-features = false, version = "0.9" }
rand_distr = { default-features = false, version = "0.5" }
# data & serialization
serde = { default-features = false, features = ["derive"], version = "1" }
serde_derive = { default-features = false, version = "1" }
serde_json = { default-features = false, version = "1" }
# macros
itertools = { default-features = false, version = "0.14" }
lazy_static = { version = "1" }
paste = { version = "1" }
smart-default = { version = "0.7" }
strum = { default-features = false, features = ["derive"], version = "0.28" }
# logging
tracing = { default-features = false, features = ["attributes"], version = "0.1" }
tracing-subscriber = {features = ["env-filter", "fmt"], version = "0.3" }
# WebAssembly
wasm-bindgen = { default-features = false, version = "0.2" }

# ************* [Profiles] *************
[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = "thin"
opt-level = 2
overflow-checks = true
panic = "abort"
rpath = true
strip = false

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = "z"
overflow-checks = false
panic = "abort"
rpath = false
strip = "debuginfo"
