[package]
build = "build.rs"
name = "rstmt"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
doc-scrape-examples = true
features = ["alloc", "complex", "hashbrown", "json", "nrt", "serde", "std", "tonnetz"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "v{{version}}"

[lib]
bench = true
crate-type = ["cdylib", "rlib", "staticlib"]
doc = true
doctest = true
name = "rstmt"
path = "lib.rs"
test = true

[[bench]]
harness = false
name = "default"
path = "benches/default.rs"

[[example]]
doc-scrape-examples = true
name = "motion"
required-features = ["std", "tonnetz"]

[[example]]
doc-scrape-examples = true
name = "triads"
required-features = ["nrt", "std"]

[dependencies]
rstmt-core = { workspace = true }
rstmt-nrt = { optional = true, workspace = true }

[dev-dependencies]
anyhow = { features = ["std"], workspace = true }
criterion = { features = ["plotters"], version = "0.8" }
lazy_static = { workspace = true }
num = { features = ["std"], version = "0.4" }
tracing = { features = ["attributes", "std"], version = "0.1" }
tracing-subscriber = { features = ["ansi", "serde", "std"], version = "0.3" }

[features]
default = [
  "nrt",
  "std",
]

full = [
  "default",
  "complex",
  "hashbrown",
  "rand",
  "serde",
  "tonnetz",
]

nightly = [
  "rstmt-core/nightly",
  "rstmt-nrt?/nightly",
]

# ************* [FF:Features] *************
nrt = [
  "dep:rstmt-nrt",
  "hashbrown",
]

tonnetz = [
  "nrt",
  "rstmt-nrt?/tonnetz",
  "std",
]

# ************* [FF:Environments] *************
std = [
  "rstmt-core/std",
  "rstmt-nrt?/std",
]

wasi = [
  "rstmt-core/wasi",
  "rstmt-nrt?/wasi",
]

wasm = [
  "rstmt-core/wasm",
  "rstmt-nrt?/wasm",
]

# ************* [FF:Dependencies] *************
alloc = [
  "rstmt-core/alloc",
  "rstmt-nrt?/alloc",
]

complex = [
  "rstmt-core/complex",
]

hashbrown = [
  "rstmt-core/hashbrown",
]

json = [
  "rstmt-core/json",
  "rstmt-nrt?/json",
]

rand = [
  "rstmt-core/rand",
  "rstmt-nrt?/rand",
]

rayon = [
  "rstmt-core/rayon",
  "rstmt-nrt?/rayon",
]

rng = [
  "rstmt-core/rng",
  "rstmt-nrt?/rng",
]

serde = [
  "rstmt-core/serde",
  "rstmt-nrt?/serde",
]

serde_json = [
  "rstmt-core/serde_json",
  "rstmt-nrt?/serde_json",
]
