[package]
build = "build.rs"
name = "rstmt"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = [ "--cfg", "docsrs" ]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "v{{version}}"

[lib]
crate-type = [
    "cdylib",
    "rlib",
    "staticlib",
]
bench = true
doc = true
doctest = true
test = true

[dependencies]
rstmt-core = { workspace = true }
rstmt-nrt = { optional = true, workspace = true }

[dev-dependencies]
anyhow = { features = ["std"], workspace = true }
criterion = { features = ["plotters"], workspace = true }
num = { features = ["std"], workspace = true }
tracing = { features = ["std"], workspace = true }
tracing-subscriber = { features = ["ansi", "serde", "std"], workspace = true }

[features]
default = [
    "nrt",
    "std",
]

full = [
    "default",
    "anyhow",
    "rand",
    "serde",
    "tracing",
]

# ************* [FF:Features] *************
nrt = [
    "dep:rstmt-nrt",
]

tonnetz = [
    "nrt",
    "rstmt-nrt?/tonnetz",
]

# ************* [FF:Environments] *************
std = [
    "rstmt-core/std",
    "rstmt-nrt?/std",
]

wasi = [
    "rstmt-core/wasi",
    "rstmt-nrt?/wasi",
]

wasm = [
    "rstmt-core/wasm",
    "rstmt-nrt?/wasm",
]


# ************* [FF:Dependencies] *************
alloc = [
    "rstmt-core/alloc",
    "rstmt-nrt?/alloc",
]

anyhow = [
    "rstmt-core/anyhow",
    "rstmt-nrt?/anyhow",
]

json = [
    "rstmt-core/json",
    "rstmt-nrt?/json",
]

rand = [
    "rstmt-core/rand",
    "rstmt-nrt?/rand",
]

rng = [
    "rstmt-core/rng",
    "rstmt-nrt?/rng",
]

serde = [
    "rstmt-core/serde",
    "rstmt-nrt?/serde",
]

serde_json = [
    "rstmt-core/serde_json",
    "rstmt-nrt?/serde_json",
]

tracing = [
    "rstmt-core/tracing",
    "rstmt-nrt?/tracing",
]

# ************* [Benchmarks] *************
[[bench]]
name = "default"
path = "benches/default.rs"
harness = false

# ************* [Examples] *************
[[example]]
name = "motion"
required-features = [
    "nrt",
    "std",
    "tracing",
]

# ************* [Examples] *************
[[example]]
name = "triads"
required-features = [
    "nrt",
    "std"
]


