[package]
build = "build.rs"
name = "rstmt-core"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std",
]

full = [
    "default",
    "rand",
    "serde",
]

# ********* [FF] Dependencies *********
alloc = [
    "num/alloc",
    "serde?/alloc",
]

rand = [
    "num/rand",
]

serde = [
    "dep:serde",
    "dep:serde_derive",
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "num/std",
    "regex/std",
    "serde?/std",
    "strum/std",
    "thiserror/std",
]

[lib]
bench = true
crate-type = [ "cdylib", "rlib" ]
doctest = false
test = true

[build-dependencies]

[dependencies]
lazy_static = { workspace = true }
num = { default-features = false, workspace = true }
paste = { workspace = true }
regex = { default-features = false, features = [ "perf", "unicode" ], version = "1" }
serde = { default-features = false, optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
smart-default = { workspace = true }
strum = { default-features = false, workspace = true }
thiserror = { default-features = false, workspace = true }

[package.metadata.docs.rs]
all-features = true
rustc-args = [ "--cfg", "docsrs" ]
