[package]
build = "build.rs"
description = "the core modules for the rstmt framework"
name = "rstmt-core"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["default"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "v{{version}}"

[lib]
bench = false
crate-type = ["lib"]
doc = true
doctest = true
test = true

[dependencies]
rstmt-traits = { workspace = true }
# custom
contained = { workspace = true }
rspace-traits = { workspace = true }
variants = { workspace = true }
# concurrency & parallelism
rayon = { optional = true, workspace = true }
# data structures
hashbrown = { optional = true, workspace = true }
# error-handling
anyhow = { workspace = true }
thiserror = { workspace = true }
# mathematics
num-complex = { optional = true, workspace = true }
num-integer = { workspace = true }
num-traits = { workspace = true }
# randomization
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
# serialization
serde = { features = ["derive"], optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# logging
tracing = { optional = true, workspace = true }
# macros & utilities
paste = { workspace = true }
smart-default = { workspace = true }
strum = { features = ["derive"], workspace = true }
# WebAssembly
wasm-bindgen = { optional = true, workspace = true }

[features]
default = [
  "hashbrown",
  "std",
]

full = [
  "default",
  "complex",
  "json",
  "macros",
  "rand",
  "serde",
  "tracing",
]

json = [
  "alloc",
  "serde",
  "serde_json",
]

nightly = [
  "hashbrown?/nightly",
  "rstmt-traits/nightly",
]

# ********* [FF] Features *********

macros = []

# ********* [FF] Environments *********

std = [
  "alloc",
  "anyhow/std",
  "contained/std",
  "hashbrown?/default",
  "getrandom?/std",
  "num-complex?/std",
  "num-integer/std",
  "num-traits/std",
  "rand?/std",
  "rand_distr?/std",
  "rspace-traits/std",
  "rstmt-traits/std",
  "serde?/std",
  "serde_json?/std",
  "strum/std",
  "tracing?/std",
  "variants/std",
]

wasi = [
  "rspace-traits/wasi",
  "rstmt-traits/wasi",
]

wasm = [
  "wasm_bindgen",
  "rspace-traits/wasm",
  "rstmt-traits/wasm",
  "getrandom?/wasm_js",
  "rayon?/web_spin_lock",
]

# ********* [FF] Dependencies *********

alloc = [
  "rstmt-traits/alloc",
  "contained/alloc",
  "hashbrown?/alloc",
  "rand?/alloc",
  "rand_distr?/alloc",
  "rspace-traits/alloc",
  "serde?/alloc",
  "serde_json?/alloc",
  "variants/alloc",
]

complex = [
  "dep:num-complex",
  "rspace-traits/complex",
]

hashbrown = [
  "dep:hashbrown",
  "rspace-traits/hashbrown",
  "rstmt-traits/hashbrown",
]

rand = [
  "rng",
  "dep:rand",
  "dep:rand_distr",
  "rspace-traits/rand",
  "rstmt-traits/rand",
  "num-complex?/rand",
]

rayon = [
  "dep:rayon",
  "hashbrown?/rayon",
  "rstmt-traits/rayon",
]

rng = [
  "dep:getrandom",
  "rand?/os_rng",
  "rand?/small_rng",
]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "serde?/derive",
  "hashbrown?/serde",
  "num-complex?/serde",
  "rand?/serde",
  "rand_distr?/serde",
  "rspace-traits/serde",
  "rstmt-traits/serde",
]

serde_json = ["dep:serde_json"]

tracing = ["dep:tracing"]

wasm_bindgen = [
  "dep:wasm-bindgen",
  "rspace-traits/wasm_bindgen",
  "rstmt-traits/wasm_bindgen",
]
