[package]
build = "build.rs"
description = "the core modules for the rstmt framework"
name = "rstmt-core"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = [
    "cdylib", 
    "rlib"
]
bench = false
doc = true
doctest = true
test = true

[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = ["--cfg", "docsrs"]

[dependencies]
# custom
scsys = { workspace = true }
# concurrency & parallelism
rayon = { optional = true, workspace = true }
# error-handling
anyhow = { optional = true, workspace = true }
thiserror = { workspace = true }
# mathematics
num = { workspace = true }
num-traits = { workspace = true }
# randomization
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
# serialization
serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# logging
tracing = { optional = true, workspace = true }
# macros & utilities
itertools = { workspace = true }
paste = { workspace = true }
strum = { features = ["derive"], workspace = true }
smart-default = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[features]
default = ["std"]

full = [
    "default", 
    "anyhow",
    "json", 
    "rand", 
    "serde", 
    "tracing",
]

# ************* [FF:Environments] *************
std = [
    "alloc",
    "num/std",
    "num-traits/std",
    "rand?/std",
    "scsys/std",
    "serde?/std",
    "strum/std",
]

wasi = [
    "scsys/wasi",
]

wasm = [
    "getrandom?/wasm_js",
    "scsys/wasm",
]
# ************* [FF:Dependencies] *************
alloc = [
    "num/alloc", 
    "scsys/alloc",
    "serde?/alloc",
    "serde_json?/alloc",
]

anyhow = [
    "dep:anyhow",
    "scsys/anyhow",
]

json = [
    "alloc",
    "serde",
    "serde_json",
    "scsys/json",
]

rand = [
    "dep:rand", 
    "dep:rand_distr", 
    "num/rand", 
    "rng", 
    "scsys/rand",
]

rng = [
    "dep:getrandom",
    "rand/small_rng", 
    "rand/thread_rng", 
    "scsys/rng",
]

serde = [
    "dep:serde", 
    "dep:serde_derive", 
    "num/serde", 
    "scsys/serde",
    "serde?/derive"
]

serde_json = ["dep:serde_json"]

tracing = [
    "dep:tracing",
    "scsys/tracing",
    "tracing?/attributes", 
    "tracing?/log"
]

# ************* [Unit Tests] *************
[[test]]
name = "default"
required-features = []
