[package]
build = "build.rs"
description = "this crate focuses on providing support for the neo-riemannian theory of music"
name = "rstmt-nrt"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["alloc", "complex", "hashbrown", "serde", "std"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "v{{version}}"

[lib]
bench = false
crate-type = ["cdylib", "rlib", "staticlib"]
doc = true
doctest = true
test = true

[dependencies]
rstmt-core = { workspace = true }
# custom
rshyper = { workspace = true }
variants = { workspace = true }
# data structures
hashbrown = { optional = true, workspace = true }
# concurrency & parallelism
rayon-core = { optional = true, workspace = true }
rayon = { optional = true, workspace = true }
# error-handling
anyhow = { workspace = true }
thiserror = { workspace = true }
# mathematics
num-complex = { optional = true, workspace = true }
num-traits = { workspace = true }
# randomization
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
# serialization
serde = { features = ["derive"], optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# macros & utilities
itertools = { workspace = true }
paste = { workspace = true }
smart-default = { workspace = true }
strum = { features = ["derive"], workspace = true }

[features]
default = ["hashbrown", "std", "tonnetz"]

full = [
  "default",
  "complex",
  "json",
  "rand",
  "serde",
]

nightly = [
  "hashbrown?/nightly",
  "rshyper/nightly",
  "rstmt-core/nightly",
]

# ************* [FF:Features] *************

tonnetz = [
  "rshyper/hyper_map",
  "std",
]

# ************* [FF:Environments] *************
std = [
  "alloc",
  "anyhow/std",
  "hashbrown?/default",
  "itertools/use_std",
  "num-complex?/std",
  "num-traits/std",
  "rand?/std",
  "rshyper/std",
  "rstmt-core/std",
  "serde?/std",
  "strum/std",
  "variants/std",
]

wasi = [
  "rstmt-core/wasi",
]

wasm = [
  "getrandom?/wasm_js",
  "rayon-core?/web_spin_lock",
  "rstmt-core/wasm",
]
# ************* [FF:Dependencies] *************
alloc = [
  "hashbrown?/alloc",
  "itertools/use_alloc",
  "rshyper/alloc",
  "rstmt-core/alloc",
  "serde?/alloc",
  "serde_json?/alloc",
  "variants/alloc",
]

complex = [
  "dep:num-complex",
  "rstmt-core/complex",
]

hashbrown = [
  "dep:hashbrown",
  "rstmt-core/hashbrown",
]

json = [
  "alloc",
  "rshyper/json",
  "rstmt-core/json",
  "serde_json",
]

rand = [
  "dep:rand",
  "dep:rand_distr",
  "num-complex?/rand",
  "rng",
  "rshyper/rand",
  "rstmt-core/rand",
]

rayon = [
  "dep:rayon",
  "dep:rayon-core",
  "hashbrown?/rayon",
  "rshyper/rayon",
  "rstmt-core/rayon",
]

rng = [
  "dep:getrandom",
  "rand/small_rng",
  "rand/thread_rng",
  "rshyper/rng",
  "rstmt-core/rng",
]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "hashbrown?/serde",
  "num-complex?/serde",
  "rshyper/serde",
  "rstmt-core/serde",
  "serde?/derive",
]

serde_json = ["dep:serde_json"]
