name: crates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  BASENAME: ${{ github.event.repository.name }}
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

jobs:
  core:
    name: Publish (${{ github.event.repository.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ core ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }}-${{ matrix.features }}
  features:
    name: Publish (${{ github.event.repository.name }})
    needs: [ core ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ neo ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }}-${{ matrix.features }}
  publish:
    name: Publish (${{ github.event.repository.name }})
    needs: [ features ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ github.event.repository.name }})
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }}