name: release

on:
  release:
    types: [published]
  repository_dispatch:
    types: [release]

permissions:
  contents: write
  discussions: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to crates.io
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: cargo-publish
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          token: ${{ github.token }}
